import assert from 'node:assert/strict';
import { addedPayment, balanceOf, needsAction, quantityOf, repeatOrderDraft } from '../src/utils/mobileOrders.js';

const order = { status: 'Deposit', grand_total: 1170, deposit: 585, order_status: 'PROCESSING', due_date: '2026-09-20', has_delivery: true, postage_status: 'PENDING', items: [{ qty: 30 }] };
assert.equal(balanceOf(order), 585);
assert.deepEqual(addedPayment(order, 185), { deposit: 770, status: 'Deposit' });
assert.deepEqual(addedPayment(order, 585), { deposit: 1170, status: 'Paid' });
for (const amount of [0, -1, 586, 'bad', Infinity]) assert.throws(() => addedPayment(order, amount));
assert.equal(quantityOf(order), 30);
assert.equal(needsAction(order, 'late', '2026-09-21'), true);
assert.equal(needsAction(order, 'late', '2026-09-20'), false);
assert.equal(needsAction({ ...order, status: 'Void' }, undefined, '2026-09-21'), false);
assert.equal(needsAction({ ...order, order_status: 'COMPLETED' }, 'dispatch'), true);
assert.equal(needsAction({ ...order, order_status: 'COMPLETED', has_delivery: false }, 'dispatch'), false);
assert.equal(needsAction({ ...order, order_status: 'COMPLETED', postage_status: 'DROPOFF' }, 'dispatch'), false);
assert.equal(needsAction({ ...order, order_status: 'COMPLETED' }, 'balance'), true);
assert.equal(balanceOf({ ...order, status: 'Paid' }), 0);
assert.deepEqual(addedPayment({ ...order, grand_total: .3, deposit: .1 }, .2), { deposit: .3, status: 'Paid' });
const repeat = repeatOrderDraft({ ...order, id: 'old', paid_date: '2026-09-21', postage_tracking: 'old-tracking', _raw_meta: { has_delivery: true } }, 'NO.00170');
assert.equal(repeat.invoice_no, 'NO.00170');
assert.equal(repeat.id, undefined);
assert.equal(repeat.paid_date, undefined);
assert.equal(repeat.postage_tracking, undefined);
assert.equal(repeat._raw_meta, undefined);
assert.equal(repeat.deposit, 0);
assert.equal(repeat.has_delivery, false);
repeat.items[0].qty = 1;
assert.equal(order.items[0].qty, 30);
console.log('Mobile checks passed: partial/full payments, invalid amounts, cents, due dates, delivery and void orders.');
