import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  EN: {
    // Sidebar
    overview: 'Overview',
    orders: 'Orders',
    manufacturing: 'Manufacturing',
    clients: 'Clients',
    ledger: 'Ledger',
    reports: 'P&L Reports',
    settings: 'Settings',
    finance: 'FINANCE',
    settingsSection: 'SETTINGS',
    localMode: 'LOCAL MODE',
    localDesc: 'Save on device',
    cloudSync: 'CLOUD SYNC',
    cloudDesc: 'Cloud Active',
    language: 'LANGUAGE',
    // Dashboard
    dashboardTag: 'MAIN CONTROL CENTER',
    dashboardTitle: 'OVERVIEW DASHBOARD',
    netProfit: 'NET PROFIT',
    netProfitDesc: 'Sales Revenue - Operating Expenses (Ledger)',
    statusBayaran: 'PAYMENT STATUS',
    statusOperasi: 'OPERATIONAL STATUS',
    unpaid: 'Unpaid',
    deposit: 'Deposit',
    paidMonth: 'Paid (This Month)',
    belumDraft: 'Belum Draft',
    draft: 'Draft',
    notSubmitted: 'Not Submit Yet',
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    maintenance: 'Under Maintenance',
    totalKutipan: 'TOTAL SALES REVENUE',
    totalKos: 'TOTAL EXPENSES',
    thisMonth: 'This Month',
    kilangLejar: 'Manufacturing + Store Ledger',
    newOrder: 'New Order',
    recentInvoices: 'Recent Invoices',
    viewAll: 'View All',
    refresh: 'Refresh Data',
    searchPlaceholder: 'Search client name or invoice number...',
    searchClientPlaceholder: 'Search client name or phone number...',
    allStatus: 'All Status',
    status: 'Status',
    month: 'Month',
    allMonths: 'All Months',
    // Orders
    ordersTag: 'ORDER LIST',
    ordersTitle: 'ORDERS',
    // Manufacturing
    mfgTag: 'MANUFACTURING & PLANT OPERATIONS',
    mfgTitle: 'MANUFACTURING',
    mfgSubtitle: 'Monitor Order Status and Production Cost Records',
    pendingOrders: 'PENDING',
    processingOrders: 'PROCESSING',
    // Clients
    clientsTag: 'CLIENT LIST',
    clientsTitle: 'CLIENTS & CRM',
    clientsSubtitle: 'Manage contact information and client order records.',
    // Ledger
    ledgerTag: 'CASHBOOK',
    ledgerTitle: 'CASHBOOK / LEDGER',
    ledgerSubtitle: 'Record store expenses and cash flow',
    // Reports
    reportsTag: 'P&L REPORTS',
    reportsTitle: 'PROFIT & LOSS STATEMENT',
    reportsSubtitle: 'Financial reports aggregated by category for official calculation.',
    // Table headers
    invNo: 'INV NO.',
    clientName: 'CLIENT NAME',
    amount: 'AMOUNT (RM)',
    status: 'STATUS',
    actions: 'ACTIONS',
    date: 'DATE',
    balance: 'BALANCE (RM)',
    phone: 'PHONE NO.',
    totalOrder: 'TOTAL ORDERS',
    totalSpent: 'TOTAL SPENT',
    items: 'ITEMS (Apparel/Banner)',
    kosKilang: 'PRODUCTION COST',
    category: 'CATEGORY',
    description: 'DESCRIPTION',
    type: 'TYPE',
    loadingInvoice: 'Loading all invoices...',
    noInvoice: 'No invoices found.',
    loadingData: 'Loading data...',
    noData: 'No records found.',
    loadingClient: 'Loading client data...',
    noClient: 'No clients found.',
    view: 'View',
    edit: 'Edit',
    delete: 'Delete',
    save: 'SAVE',
    print: 'PRINT',
    previous: 'Previous',
    next: 'Next',
    cancel: 'Cancel',
    saveChanges: 'Save Changes',
    close: 'Close',
    addExpense: 'ADD EXPENSE (Rent, Salary, Bills, etc)',
    editInfo: 'Edit Info',
    saveInvoice: 'Save Invoice',
    saveRecord: 'Save Record',
    saveSettings: 'Save Settings',
    printReport: 'Print Report',
    // Settings Page
    sysConfig: 'System Configuration',
    settingsTitle: 'Settings',
    compInfo: '1. Company & Store Info',
    compName: 'Company Name',
    phoneNo: 'Phone Number',
    storeAddress: 'Store Address',
    compLogo: 'Company Logo (Max 500KB)',
    uploadLogo: 'Upload Logo',
    invoicePrefix: 'Invoice Number Prefix',
    invoicePrefixHelp: 'Prefix for invoice numbers (e.g., NO.00001)',
    paymentInfo: '2. Payment Information',
    bankName: 'Bank Name',
    bankAccNo: 'Bank Account No.',
    accName: 'Account Name',
    qrCode: 'DuitNow QR Code (Max 500KB)',
    uploadQR: 'Upload QR Code',
    termsTitle: '3. Store Terms & Conditions (Invoice Notes)',
    termsLabel: 'Business Rules & Conditions',
    termsHelp: 'One sentence per line. This text will be printed at the bottom of the invoice.',
    dbTitle: '4. Supabase Database Integration (Cloud)',
    dbDesc: 'Enter your Supabase database details to enable data synchronization across devices (store computer and mobile). If left empty, the system will revert to **LocalStorage Mode**.',
    testConnection: 'Test Connection',
    testingDb: 'Testing database connection...',
    backupTitle: '5. Data Backup & Restore',
    backupDesc: 'Use this function to download all your data records to your computer for safekeeping, or restore old data if you change devices or clear your web browser.',
    downloadBackup: 'Download Data (Export JSON)',
    uploadRestore: 'Upload Data (Import JSON)',
    settingsSaved: 'Settings saved successfully!',
  },
  BM: {
    // Sidebar
    overview: 'Utama',
    orders: 'Tempahan',
    manufacturing: 'Kilang',
    clients: 'Pelanggan',
    ledger: 'Lejar (Buku)',
    reports: 'Laporan P&L',
    settings: 'Tetapan',
    finance: 'KEWANGAN',
    settingsSection: 'TETAPAN',
    localMode: 'MODE LOKAL',
    localDesc: 'Simpan peranti',
    cloudSync: 'SINKRON AWAN',
    cloudDesc: 'Awan aktif',
    language: 'BAHASA / LANGUAGE',
    // Dashboard
    dashboardTag: 'PUSAT KAWALAN UTAMA',
    dashboardTitle: 'PAPAN KAWALAN',
    netProfit: 'UNTUNG BERSIH SEBENAR',
    netProfitDesc: 'Kutipan Jualan - Kos Operasi (Lejar)',
    statusBayaran: 'STATUS BAYARAN',
    statusOperasi: 'STATUS OPERASI',
    unpaid: 'Belum Bayar',
    deposit: 'Deposit',
    paidMonth: 'Lunas (Bulan ini)',
    belumDraft: 'Belum Draft',
    draft: 'Draft',
    notSubmitted: 'Belum Submit',
    pending: 'Belum Mula',
    processing: 'Sedang Jalan',
    completed: 'Siap',
    maintenance: 'Dalam Penyelenggaraan',
    totalKutipan: 'TOTAL KUTIPAN JUALAN',
    totalKos: 'TOTAL KOS (KELUAR)',
    thisMonth: 'Bulan ini',
    kilangLejar: 'Kilang + Lejar Kedai',
    newOrder: 'Tempahan Baru',
    recentInvoices: 'Tempahan Terkini',
    viewAll: 'Lihat Semua',
    refresh: 'Muat Semula',
    searchPlaceholder: 'Cari nama pelanggan atau no. invois...',
    searchClientPlaceholder: 'Cari nama atau nombor telefon pelanggan...',
    allStatus: 'Semua Status',
    status: 'Status',
    month: 'Bulan',
    allMonths: 'Semua Bulan',
    // Orders
    ordersTag: 'SENARAI TEMPAHAN',
    ordersTitle: 'TAMPAHAN',
    // Manufacturing
    mfgTag: 'MANUFACTURING & OPERASI KILANG',
    mfgTitle: 'KILANG',
    mfgSubtitle: 'Pantau Status Tempahan dan Rekod Kos Pengeluaran',
    pendingOrders: 'PENDING (Belum)',
    processingOrders: 'PROCESSING (Jalan)',
    // Clients
    clientsTag: 'SENARAI PELANGGAN',
    clientsTitle: 'PELANGGAN & CRM',
    clientsSubtitle: 'Urus maklumat hubungan dan rekod tempahan pelanggan.',
    // Ledger
    ledgerTag: 'BUKU LEJAR',
    ledgerTitle: 'TUNAI / BUKU TUNAI',
    ledgerSubtitle: 'Rekod perbelanjaan kedai dan aliran tunai',
    // Reports
    reportsTag: 'LAPORAN P&L',
    reportsTitle: 'PENYATA UNTUNG RUGI',
    reportsSubtitle: 'Laporan kewangan yang dikumpul ikut kategori untuk pengiraan rasmi.',
    // Table headers
    invNo: 'NO. INV',
    clientName: 'NAMA PELANGGAN',
    amount: 'JUMLAH (RM)',
    status: 'STATUS',
    actions: 'TINDAKAN',
    date: 'TARIKH',
    balance: 'BAKI (RM)',
    phone: 'NO. TELEFON',
    totalOrder: 'JUMLAH TEMPAHAN',
    totalSpent: 'JUMLAH BELANJA',
    items: 'ITEM (Baju/Banner)',
    kosKilang: 'KOS KILANG',
    category: 'KATEGORI',
    description: 'KETERANGAN',
    type: 'JENIS',
    loadingInvoice: 'Memuatkan semua invois...',
    noInvoice: 'Tiada invois ditemui.',
    loadingData: 'Memuatkan data...',
    noData: 'Tiada rekod ditemui.',
    loadingClient: 'Memuatkan data pelanggan...',
    noClient: 'Tiada pelanggan ditemui.',
    view: 'Lihat',
    edit: 'Edit',
    delete: 'Padam',
    save: 'SIMPAN',
    print: 'CETAK',
    previous: 'Sebelum',
    next: 'Seterusnya',
    cancel: 'Batal',
    saveChanges: 'Simpan Perubahan',
    close: 'Tutup',
    addExpense: 'TAMBAH PERBELANJAAN (Sewa, Gaji, Bil, dll)',
    editInfo: 'Edit Maklumat',
    saveInvoice: 'Simpan Invoice',
    saveRecord: 'Simpan Rekod',
    saveSettings: 'Simpan Tetapan',
    printReport: 'Cetak Laporan',
    // Settings Page
    sysConfig: 'Konfigurasi Sistem',
    settingsTitle: 'Settings & Tetapan',
    compInfo: '1. Maklumat Syarikat & Kedai',
    compName: 'Nama Syarikat',
    phoneNo: 'No. Telefon',
    storeAddress: 'Alamat Kedai',
    compLogo: 'Logo Syarikat (Maksimum 500KB)',
    uploadLogo: 'Muat Naik Logo',
    invoicePrefix: 'Prefix Nombor Invoice',
    invoicePrefixHelp: 'Prefix hadapan bagi nombor invoice (cth: NO.00001)',
    paymentInfo: '2. Maklumat Pembayaran',
    bankName: 'Nama Bank',
    bankAccNo: 'No. Akaun Bank',
    accName: 'Nama Akaun',
    qrCode: 'Kod QR DuitNow (Maksimum 500KB)',
    uploadQR: 'Muat Naik Kod QR',
    termsTitle: '3. Terma & Syarat Kedai (Nota Invoice)',
    termsLabel: 'Syarat & Peraturan Perniagaan',
    termsHelp: 'Satu ayat per baris. Teks ini akan dicetak di bahagian nota kaki invoice.',
    dbTitle: '4. Integrasi Pangkalan Data Supabase (Awan)',
    dbDesc: 'Masukkan maklumat pangkalan data Supabase anda untuk mengaktifkan penyegerakan data di antara peranti (komputer kedai dan telefon bimbit). Jika dikosongkan, sistem akan kembali kepada **Mod LocalStorage**.',
    testConnection: 'Uji Sambungan',
    testingDb: 'Sedang menguji sambungan database...',
    backupTitle: '5. Sandaran Data (Backup & Restore)',
    backupDesc: 'Gunakan fungsi ini untuk memuat turun semua rekod data anda ke fail komputer anda bagi keselamatan, atau memulihkan data lama sekiranya anda menukar peranti atau melaraskan pelayar web.',
    downloadBackup: 'Muat Turun Data (Export JSON)',
    uploadRestore: 'Muat Naik Data (Import JSON)',
    settingsSaved: 'Tetapan berjaya disimpan!',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('EN');

  const tr = (key) => {
    const table = translations[language] || translations.EN;
    return table[key] !== undefined ? table[key] : (translations.EN[key] !== undefined ? translations.EN[key] : key);
  };

  const toggleLanguage = () => {
    setLanguage(prev => (prev === 'EN' ? 'BM' : 'EN'));
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, tr }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
